// <auto-generated />
using System;
using InventoryDatabase.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryDatabase.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20251105054502_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InventoryDomain.InventoryEntities.Caja", b =>
                {
                    b.Property<int>("CajaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CajaId"));

                    b.Property<int>("CantidadBackorder")
                        .HasColumnType("int");

                    b.Property<int>("CantidadReferencias")
                        .HasColumnType("int");

                    b.Property<string>("CodigoCaja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DocumentoTransporteId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaInsercion")
                        .HasColumnType("datetime2");

                    b.HasKey("CajaId");

                    b.HasIndex("DocumentoTransporteId");

                    b.ToTable("Cajas");
                });

            modelBuilder.Entity("InventoryDomain.InventoryEntities.DocumentoTransporte", b =>
                {
                    b.Property<int>("TrasnporDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrasnporDocumentId"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrasnporDocumentId");

                    b.ToTable("DocumentosTransporte");
                });

            modelBuilder.Entity("InventoryDomain.InventoryEntities.Referencia", b =>
                {
                    b.Property<int>("ReferenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReferenciaId"));

                    b.Property<int>("CajaId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoReferencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreReferencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TieneBackorder")
                        .HasColumnType("bit");

                    b.HasKey("ReferenciaId");

                    b.HasIndex("CajaId");

                    b.ToTable("Referencias");
                });

            modelBuilder.Entity("InventoryDomain.InventoryEntities.Caja", b =>
                {
                    b.HasOne("InventoryDomain.InventoryEntities.DocumentoTransporte", "DocumentoTransporte")
                        .WithMany("Cajas")
                        .HasForeignKey("DocumentoTransporteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentoTransporte");
                });

            modelBuilder.Entity("InventoryDomain.InventoryEntities.Referencia", b =>
                {
                    b.HasOne("InventoryDomain.InventoryEntities.Caja", "Caja")
                        .WithMany("Referencias")
                        .HasForeignKey("CajaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caja");
                });

            modelBuilder.Entity("InventoryDomain.InventoryEntities.Caja", b =>
                {
                    b.Navigation("Referencias");
                });

            modelBuilder.Entity("InventoryDomain.InventoryEntities.DocumentoTransporte", b =>
                {
                    b.Navigation("Cajas");
                });
#pragma warning restore 612, 618
        }
    }
}
